[colors]
background = '#141515'
foreground = '#ddd0c4'
selection-background = '#515151'
selection-foreground = '#ffc663'
cursor = '#702420'
black = '#333333'
red = '#b66056'
green = '#85b1a9'
yellow = '#dbbb43'
blue = '#6890d7'
magenta = '#887aa3'
cyan = '#837369'
white = '#ddd0c4'
light_black = '#515151'
light_red = '#ffc663'
light_green = '#c1ffae'
light_yellow = '#fff700'
light_blue = '#a1d9ff'
light_magenta = '#a994ff'
light_cyan = '#f9cfb9'
light_white = '#ffffff'
