[colors]
background = '#111147'
foreground = '#db7ddd'
selection-background = '#5ca8dc'
selection-foreground = '#d0beee'
cursor = '#53b397'
black = '#111147'
red = '#5ca8dc'
green = '#53b397'
yellow = '#249a84'
blue = '#db7ddd'
magenta = '#d0beee'
cyan = '#f9f3f9'
white = '#a175d4'
light_black = '#111147'
light_red = '#5cb5dc'
light_green = '#52deb5'
light_yellow = '#01f5c7'
light_blue = '#fa5dfd'
light_magenta = '#c6a5fd'
light_cyan = '#ffffff'
light_white = '#b577fd'
